"""initial schema

Revision ID: 8c8fe298cbed
Revises: 
Create Date: 2026-05-12 19:16:41.660067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8fe298cbed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_confirmation_token', sa.String(length=100), nullable=True),
    sa.Column('subscription_plan', sa.String(length=20), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_backup_codes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_confirmation_token'),
    sa.UniqueConstraint('password_reset_token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('nis2_audit_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_audit_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_audit_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nis2_audit_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_bsi_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('legal_form', sa.String(length=50), nullable=True),
    sa.Column('hrb_number', sa.String(length=50), nullable=True),
    sa.Column('registry_court', sa.String(length=100), nullable=True),
    sa.Column('vat_id', sa.String(length=30), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue_eur', sa.BigInteger(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('is_affected', sa.Boolean(), nullable=True),
    sa.Column('contacts_json', sa.Text(), nullable=True),
    sa.Column('technical_json', sa.Text(), nullable=True),
    sa.Column('wizard_step', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_bsi_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_bsi_registrations_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('incident_ref', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('affected_systems', sa.Text(), nullable=True),
    sa.Column('affected_data', sa.Text(), nullable=True),
    sa.Column('affected_systems_json', sa.Text(), nullable=True),
    sa.Column('affected_data_categories_json', sa.Text(), nullable=True),
    sa.Column('mitigation_steps', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('eradicated_at', sa.DateTime(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('fruehwarnung_deadline', sa.DateTime(), nullable=True),
    sa.Column('zwischenmeldung_deadline', sa.DateTime(), nullable=True),
    sa.Column('abschlussbericht_deadline', sa.DateTime(), nullable=True),
    sa.Column('fruehwarnung_sent', sa.Boolean(), nullable=True),
    sa.Column('zwischenmeldung_sent', sa.Boolean(), nullable=True),
    sa.Column('abschlussbericht_sent', sa.Boolean(), nullable=True),
    sa.Column('dsgvo_relevant', sa.Boolean(), nullable=True),
    sa.Column('dpa_notification_required', sa.Boolean(), nullable=True),
    sa.Column('dpa_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('dpa_notification_deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_ref')
    )
    with op.batch_alter_table('nis2_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_nis2_incidents_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_isms_interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('company_profile_json', sa.Text(), nullable=True),
    sa.Column('it_landscape_json', sa.Text(), nullable=True),
    sa.Column('security_level_json', sa.Text(), nullable=True),
    sa.Column('risk_assessment_json', sa.Text(), nullable=True),
    sa.Column('current_phase', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('requested_docs_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_isms_interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_isms_interviews_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_it_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('is_internet_facing', sa.Boolean(), nullable=True),
    sa.Column('stores_personal_data', sa.Boolean(), nullable=True),
    sa.Column('last_patched_at', sa.Date(), nullable=True),
    sa.Column('next_patch_due', sa.Date(), nullable=True),
    sa.Column('known_vulnerabilities', sa.Text(), nullable=True),
    sa.Column('patch_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('decommissioned_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_it_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_it_assets_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_monitoring_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scan_frequency', sa.String(length=20), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('next_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('alert_on_degradation', sa.Boolean(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('alert_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_monitoring_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_monitoring_targets_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('vat_id', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('services_provided', sa.Text(), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('vies_valid', sa.Boolean(), nullable=True),
    sa.Column('sanctions_clear', sa.Boolean(), nullable=True),
    sa.Column('registry_active', sa.Boolean(), nullable=True),
    sa.Column('last_verification_at', sa.DateTime(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('has_iso27001', sa.Boolean(), nullable=True),
    sa.Column('has_soc2', sa.Boolean(), nullable=True),
    sa.Column('has_bsi_grundschutz', sa.Boolean(), nullable=True),
    sa.Column('tls_grade', sa.String(length=5), nullable=True),
    sa.Column('last_security_scan_at', sa.DateTime(), nullable=True),
    sa.Column('avv_exists', sa.Boolean(), nullable=True),
    sa.Column('avv_signed_at', sa.Date(), nullable=True),
    sa.Column('avv_review_due', sa.Date(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors_json', sa.Text(), nullable=True),
    sa.Column('last_assessment_at', sa.DateTime(), nullable=True),
    sa.Column('verification_results_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_suppliers_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('audience_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('gf_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('gf_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('gf_acknowledged_name', sa.String(length=200), nullable=True),
    sa.Column('gf_acknowledged_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_trainings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_trainings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_nis2_trainings_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_audit_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('severity_rank', sa.Integer(), nullable=True),
    sa.Column('cvss', sa.String(length=30), nullable=True),
    sa.Column('dsgvo_article', sa.String(length=200), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('tool', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['nis2_audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_audit_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_audit_findings_job_id'), ['job_id'], unique=False)

    op.create_table('nis2_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['nis2_audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_audit_logs_job_id'), ['job_id'], unique=False)

    op.create_table('nis2_audit_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nis2_ref', sa.String(length=100), nullable=True),
    sa.Column('dsgvo_ref', sa.String(length=100), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['nis2_audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_audit_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_audit_tasks_job_id'), ['job_id'], unique=False)

    op.create_table('nis2_incident_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('generated_by_ai', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('bsi_reference', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['nis2_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_incident_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_incident_drafts_incident_id'), ['incident_id'], unique=False)

    op.create_table('nis2_incident_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['nis2_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_incident_timeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_incident_timeline_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nis2_incident_timeline_timestamp'), ['timestamp'], unique=False)

    op.create_table('nis2_isms_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('bsi_standard_ref', sa.String(length=30), nullable=True),
    sa.Column('nis2_paragraph_ref', sa.String(length=30), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_interval_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['nis2_isms_interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_isms_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_isms_documents_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_monitoring_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('diff_json', sa.Text(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('high_count', sa.Integer(), nullable=True),
    sa.Column('medium_count', sa.Integer(), nullable=True),
    sa.Column('low_count', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['nis2_monitoring_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_monitoring_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_monitoring_scans_target_id'), ['target_id'], unique=False)

    op.create_table('nis2_processing_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.String(length=50), nullable=True),
    sa.Column('legal_basis_notes', sa.Text(), nullable=True),
    sa.Column('data_categories_json', sa.Text(), nullable=True),
    sa.Column('data_subject_types_json', sa.Text(), nullable=True),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('third_country_transfer', sa.Boolean(), nullable=True),
    sa.Column('third_country_safeguards', sa.Text(), nullable=True),
    sa.Column('retention_period', sa.String(length=200), nullable=True),
    sa.Column('deletion_process', sa.Text(), nullable=True),
    sa.Column('technical_measures', sa.Text(), nullable=True),
    sa.Column('processor_id', sa.Integer(), nullable=True),
    sa.Column('processor_name', sa.String(length=300), nullable=True),
    sa.Column('is_high_risk', sa.Boolean(), nullable=True),
    sa.Column('dsfa_done', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['processor_id'], ['nis2_suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_processing_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_processing_activities_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('affected_asset', sa.String(length=200), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('treatment_type', sa.String(length=20), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('residual_likelihood', sa.Integer(), nullable=True),
    sa.Column('residual_impact', sa.Integer(), nullable=True),
    sa.Column('risk_owner', sa.String(length=200), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nis2_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['nis2_it_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_risks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_risks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_nis2_risks_user_id'), ['user_id'], unique=False)

    op.create_table('nis2_supplier_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['nis2_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_supplier_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_supplier_assessments_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('nis2_training_acks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=False),
    sa.Column('recipient_email', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('confirmed_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['nis2_trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nis2_training_acks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nis2_training_acks_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_nis2_training_acks_training_id'), ['training_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nis2_training_acks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_training_acks_training_id'))
        batch_op.drop_index(batch_op.f('ix_nis2_training_acks_token'))

    op.drop_table('nis2_training_acks')
    with op.batch_alter_table('nis2_supplier_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_supplier_assessments_supplier_id'))

    op.drop_table('nis2_supplier_assessments')
    with op.batch_alter_table('nis2_risks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_risks_user_id'))
        batch_op.drop_index(batch_op.f('ix_nis2_risks_status'))

    op.drop_table('nis2_risks')
    with op.batch_alter_table('nis2_processing_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_processing_activities_user_id'))

    op.drop_table('nis2_processing_activities')
    with op.batch_alter_table('nis2_monitoring_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_monitoring_scans_target_id'))

    op.drop_table('nis2_monitoring_scans')
    with op.batch_alter_table('nis2_isms_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_isms_documents_user_id'))

    op.drop_table('nis2_isms_documents')
    with op.batch_alter_table('nis2_incident_timeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_incident_timeline_timestamp'))
        batch_op.drop_index(batch_op.f('ix_nis2_incident_timeline_incident_id'))

    op.drop_table('nis2_incident_timeline')
    with op.batch_alter_table('nis2_incident_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_incident_drafts_incident_id'))

    op.drop_table('nis2_incident_drafts')
    with op.batch_alter_table('nis2_audit_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_audit_tasks_job_id'))

    op.drop_table('nis2_audit_tasks')
    with op.batch_alter_table('nis2_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_audit_logs_job_id'))

    op.drop_table('nis2_audit_logs')
    with op.batch_alter_table('nis2_audit_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_audit_findings_job_id'))

    op.drop_table('nis2_audit_findings')
    with op.batch_alter_table('nis2_trainings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_trainings_user_id'))
        batch_op.drop_index(batch_op.f('ix_nis2_trainings_status'))

    op.drop_table('nis2_trainings')
    with op.batch_alter_table('nis2_suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_suppliers_user_id'))

    op.drop_table('nis2_suppliers')
    with op.batch_alter_table('nis2_monitoring_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_monitoring_targets_user_id'))

    op.drop_table('nis2_monitoring_targets')
    with op.batch_alter_table('nis2_it_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_it_assets_user_id'))

    op.drop_table('nis2_it_assets')
    with op.batch_alter_table('nis2_isms_interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_isms_interviews_user_id'))

    op.drop_table('nis2_isms_interviews')
    with op.batch_alter_table('nis2_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_incidents_user_id'))
        batch_op.drop_index(batch_op.f('ix_nis2_incidents_status'))

    op.drop_table('nis2_incidents')
    with op.batch_alter_table('nis2_bsi_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_bsi_registrations_user_id'))

    op.drop_table('nis2_bsi_registrations')
    with op.batch_alter_table('nis2_audit_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nis2_audit_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_nis2_audit_jobs_created_at'))

    op.drop_table('nis2_audit_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
